### PR TITLE
adding check for imageURL length

### PR DESCRIPTION
**Pull request by greengangsta**
*Issue #, if available:*

*Description of changes:*

Assigning imgUrlLength to 0 in case image URL is not provided in the Response card. 

Fixes : https://github.com/aws-solutions/qnabot-on-aws/issues/492

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by rstrahan — CHANGES_REQUESTED** [review]
Line 476 should also incorporate his fix by @bobpskier see https://github.com/aws-solutions/qnabot-on-aws/issues/492#issuecomment-1232939689

The use of out.messages[1] in line 476 assumes the messages array is of size 1 which might not be the case. While QnABot might only support one message, a Lambda code hook called by QnABot might very well add a second message for LexV2 to process.

**Review by rstrahan — APPROVED** [review]
Looks good to me.. Thanks @greengangsta ! 
@bobpskier  - does this PR look good to you? Should be exactly the change you recommended on the issue thread.
Thanks all!

**Comment by bobpskier** [comment]
@rstrahan @greengangsta The changes look good to me as well. Once they are merged into the develop branch I can pull and test against my dev site.

**Comment by tabdunabi** [comment]
Hi @greengangsta, FYI, I have changed the branch base for your PR to the `develop` branch. Typically, we merge code to `develop` branch first, and later to `main` branch after testing. 
Thanks!.

**Review by tabdunabi — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
