### PR TITLE
Secure cognito roles

### PR DESCRIPTION
**Pull request by amendlik**
*Issue #, if available:* N/A

*Description of changes:* Eliminate warnings for missing IAM conditions on roles created for Cognito.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by marcburnie** [comment]
Thanks @amendlik for your contribution! We will review and get back to you.

**Comment by abhirpat** [comment]
Hi @amendlik , I'm reviewing this PR. To add background, could you please let us know where you received these warnings?

Thank you,
Abhishek

**Comment by amendlik** [comment]
It's been 3 months since I made this change, so my memory may be a little fuzzy. It was in the AWS Console, either in the Cognito UI or the IAM UI for those roles.

**Comment by abhirpat** [comment]
Hi @amendlik  , this issue should be addressed with the latest release v6.0.0. Please refer to [CHANGELOG](https://github.com/aws-solutions/qnabot-on-aws/blob/main/CHANGELOG.md) for additional details about this release. Thank You!

**Pull request closed without merging**
